[cliente_classico]
cliente_classico_1 ansible_host=192.168.56.11
cliente_classico_2 ansible_host=192.168.57.12

[cliente_malicioso]
cliente_malicioso ansible_host=192.168.56.66

[infra]
roteador ansible_host=192.168.56.1
servidor ansible_host=192.168.57.20

[all:vars]
ansible_user=vagrant
# Para execucao manual do playbook, gere um SSH config com:
# vagrant ssh-config > .vagrant/ssh-config
# E execute:
# ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --ssh-common-args='-F .vagrant/ssh-config'
